image: docker:latest

services:
  - docker:dind

stages:
  - test

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  COMPOSE_PROJECT_NAME: "gtbaita"

test:
  stage: test
  script: |
    docker compose -f docker/docker-compose.yml up --build -d

    echo "Instalando dependências Composer..."
    docker compose -f docker/docker-compose.yml exec ps composer install --optimize-autoloader || exit 1
    echo "Dependências instaladas."

    echo "Aguardando o PS subir (verificando php artisan)..."
    count=0
    ready=false
    while [ $count -lt 60 ]; do
      if docker compose -f docker/docker-compose.yml exec ps php artisan --version >/dev/null 2>&1; then
        echo "PS pronto!"
        ready=true
        break
      fi
      echo "Aguardando..."
      sleep 1
      count=$((count+1))
    done

    if [ "$ready" = false ]; then
       echo "Timeout aguardando o PS. Exibindo logs para depuração:"
       docker compose -f docker/docker-compose.yml logs ps
       exit 1
    fi

    docker compose -f docker/docker-compose.yml exec ps composer self-update
    docker compose -f docker/docker-compose.yml exec ps composer require --dev phpunit/phpunit

    echo "Executando testes..."
    docker compose -f docker/docker-compose.yml exec ps php artisan test --env=testing || exit 1
  only:
    - main

  after_script:
    - echo "Limpando containers..."
    - docker compose -f docker/docker-compose.yml down --volumes --remove-orphans
