image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  COMPOSE_PROJECT_NAME: "gtbaita"

before_script:
  - apk add --no-cache docker-compose

build:
  stage: build
  script:
    - docker-compose -f docker/docker-compose.yml build
  only:
    - main

test:
  stage: test
  script:
    - docker compose -f docker/docker-compose.yml up -d
    - echo "Aguardando o PS subir..."
      for i in {1..30}; do
      if docker compose -f docker/docker-compose.yml exec ps php artisan --version >/dev/null 2>&1; then
      echo "PS pronto!"
      break
      fi
      echo "Aguardando..."
      sleep 2
      done
    - docker compose -f docker/docker-compose.yml exec ps php artisan test --env=testing
  only:
    - main
