services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    networks:
      - laravel
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpass"] # Verifica se o mysql está respondendo na URL
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 10s
    

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev --features=scripts
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - laravel

  terraform:
    build:
      context: ../terraform
      dockerfile: Dockerfile
    volumes:
      - ../terraform:/workspace
    depends_on:
      - keycloak
    networks:
      - laravel
      
  ps:
    build:
      context: ../ps
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ../ps:/var/www
    ports:
      - "8081:8000"
    networks:
      - laravel
    depends_on:
      mysql:
        condition: service_healthy
      terraform:
        condition: service_completed_successfully

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data: