version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: start-dev --features=scripts #habilita recursos de script 
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - laravel

  terraform:
    build:
      context: ../terraform
      dockerfile: Dockerfile
    volumes:
      - ../terraform:/workspace
    depends_on:
      - keycloak
    networks:
      - laravel
      
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    networks:
      - laravel
    volumes:
      - mysql_data:/var/lib/mysql

  ps:
    build:
      context: ../ps
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ../ps:/var/www
    ports:
      - "8081:8000"
    networks:
      - laravel
    depends_on:
      - mysql
      - terraform

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data: