version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: start-dev --features=scripts #habilita recursos de script 
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

  ps:
    build:
      context: ../ps
      dockerfile: ../ps/Dockerfile
    working_dir: /var/www
    volumes:
      - ../ps:/var/www
    ports:
      - "8081:8000"



networks:
  laravel:
    driver: bridge